# GET http://localhost:5001/general/user

POST http://localhost:5001/general/user
Content-Type: application/json

{
  "name": "Lebron",
  "email": "acb@gmail.com",
  "password": "hfhahf23",
  "picturePath": "linkedIn",
  "phoneNumber": "02-12348299",
  "occupation": "software engineer"
}


